env: dataproc
gcs_bucket: 'gs://dataproc-staging-us-central1-40371648517-ndvgfbwp'
raw_extracted_path: 'gs://dataproc-staging-us-central1-40371648517-ndvgfbwp/notebooks/jupyter/FEC-Campaign-Analysis/FEC-Data/raw_extracted/'
bronze_path: 'gs://dataproc-staging-us-central1-40371648517-ndvgfbwp/notebooks/jupyter/FEC-Campaign-Analysis/FEC-Data/bronze/'
silver_path: 'gs://dataproc-staging-us-central1-40371648517-ndvgfbwp/notebooks/jupyter/FEC-Campaign-Analysis/FEC-Data/silver/'
gold_path: 'gs://dataproc-staging-us-central1-40371648517-ndvgfbwp/notebooks/jupyter/FEC-Campaign-Analysis/FEC-Data/gold/'

spark:
  default_app_name: fecPipeline
  shuffle_partitions: 80 
  dynamic_allocation: true
  driver_memory: '4g'
  executor_memory: '5g'
  executor_cores: 2
mysql_config:
  user: FECdb_skydiffer
  password: 59516476a3c6b819f20091965dbb0d608624eb56
  host: i2ejh.h.filess.io
  port: 61001
  database: FECdb_skydiffer
  driver: pymysql